language: node_js
node_js: 9
deploy:
  provider: pages
  local_dir: build
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: tituswormer@gmail.com
  name: Titus Wormer
  on:
    branch: src
