name: main
on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 7 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm install
      - run: npm test
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          OC_TOKEN: ${{secrets.OC_TOKEN}}
          UNIFIED_OPTIMIZE_IMAGES: 1
      - uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: dist
          commit-message: .
          folder: build
          git-config-email: tituswormer@gmail.com
          git-config-name: Titus Wormer
          single-commit: true
